### ISSUE TITLE
Can't specify library separately.

### ISSUE THREAD

**Issue by ReneeVandervelde** [tebru/retrofit-php-bundle#3]
If you specify the library separately, as recommended by the docs. If you do, you'll get a version conflict.

``` shell
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tebru/retrofit-bundle dev-master requires tebru/retrofit-php 0.2.* -> no matching package found.
    - tebru/retrofit-bundle dev-master requires tebru/retrofit-php 0.2.* -> no matching package found.
    - Installation request for tebru/retrofit-bundle dev-master -> satisfiable by tebru/retrofit-bundle[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by natebrunette** [comment]
I believe this is an issue with minimum stability settings in your composer.json.  Specifying a stable version number (e.g. `composer require tebru/retrofit-php:0.2.* tebru/retrofit-bundle:0.1.*`) resolves successfully using a default symfony installation.

**Comment by ReneeVandervelde** [comment]
@natebrunette I think you've completely missed my point.

In your readme, you include the line:

> Please include both packages in your composer.json file so you can update the library separately.

But in the project's dependencies you have configured:

```
"tebru/retrofit-php": "0.2.*"
```

So either this needs to change, or it needs to be more flexible of a definition for it to work.
